public class exampleCon {

    public String count { get; set; }
    String uname;

    public String getUsername() {
        return uname;
    }
            
                
    public void setState(String n) {
        state = n;
    }
            
    public String getState() {
        return state;
    }
            
    public PageReference methodOne() {
        return null;
    }
            
    private String state = 'no';
}